### PR TITLE
Update to Reboot v4.3.1 and other changes

### PR DESCRIPTION
**Pull request by z0al**
Hello,

I started my fork mainly to update `reboot.css` to the latest version, but later found myself made other changes. 

Changes:

* Reboot v4.3.1
* No bundling, we clone a minified `reboot.css`
* Added bootstrap as a dev dependency. The idea is to set up [Greenkeeper](https://greenkeeper.io/) to notify us of new bootstrap versions.
* Automatic release with [semantic-release](https://npm.im/semantic-release) with the help of [Travis CI](https://travis-ci.org)
* Added a `download` script to automatically clone the latest minified `reboot.css`, and a tiny test to make sure it works.
* `package-lock.json` instead of `yarn.lock` 

So, to merge this PR, you need to:

1. Setup [Travis CI for semantic releasing](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration).
2. Setup [Greenkeeeper.io](https://greenkeeper.io/)

**No pressure**. If you think those changes are too much or may don't like the way I did things feel free to reject this PR.

### CODE REVIEW

**Comment by z0al** [comment]
This is weird. I've no idea how to mark the PR as read-for-review. I thought there should a button somewhere here 0_o

**Comment by erquhart** [comment]
Weird, the Ready for review button is supposed to be showing for you, but instead they're showing it to me. That's new.

Anywhow, it looks like this repo is now obsolete - Bootstrap is providing a built copy of Reboot in their npm distribution: https://unpkg.com/bootstrap/dist/css/bootstrap-reboot.css

Going to add that link to the top of the readme and archive this puppy. If you feel I'm missing something and this repo still serves an unserved use case, let me know.

**Comment by erquhart** [comment]
Ah, nevermind, I see your PR is pulling from Bootstrap. I suppose it's worth being able to use Reboot without having the weight of Bootstrap as a dev dependency in your project. Awesome work on this PR - I'll get Travis and Greenkeeper set up soon 👍

**Review by erquhart — APPROVED** [review]
Looks great, thanks @z0al 👍 👍

**Comment by erquhart** [comment]
@z0al I use 2FA in npm, so semantic release won't work (https://github.com/semantic-release/npm/issues/93). (Others have come to the [same conclusion](https://github.com/sindresorhus/normalize-url/pull/82#issuecomment-448264780)). We need to think of a way to do this with manual releases.

**Comment by erquhart** [comment]
Update: added you as a collaborator so you can hook up publishing if you don't use 2FA on npm.

**Pull request merged**
